spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.128:3306/xc-content?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: cwb
mybatis-plus:
  global-config:
    db-config:
      insert-fill: field-fill  # 启用插入填充策略
      update-fill: field-fill  # 启用更新填充策略